name: Sync Fork
 
on:
  schedule:
    - cron: "0 0 * * *" # 每天午夜运行
  workflow_dispatch: # 允许手动触发
 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout original repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 获取所有历史记录，以便找到所有分支和标签
      - name: Sync fork with upstream changes
        run: |
          git remote add upstream https://github.com/LibreSpark/LibreTV.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main --force
